#!/bin/sh

CONFIG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/wolwizard"
HISTORY_FILE="$CONFIG_DIR/history"
FILE="$XDG_STATE_HOME"

if [ ! -f "$CONFIG_DIR" ]; then
    mkdir -p "$CONFIG_DIR"
fi

MENU_TITLE="Select an Option"
MENU_PROMPT="Choose one:"
HEIGHT=20
WIDTH=60
CHOICE_HEIGHT=10

i=0
MENU_ITEMS=""
while IFS= read -r line; do
	[ -z "$line" ] && continue
	MENU_ITEMS="$MENU_ITEMS $i \"$line\""
	i=$((i + 1))
done <<EOF
Enter a MAC address manually
$( [ -f "$HISTORY_FILE" ] && cat "$HISTORY_FILE" )
EOF

echo $MENU_ITEMS

# shellcheck disable=SC2086
CHOICE=$(eval dialog \
    --backtitle "\"WOLWizard\"" \
    --title "\"$MENU_TITLE\"" \
    --menu "\"$MENU_PROMPT\"" \
    20 $WIDTH 10 \
    $MENU_ITEMS \
    3>&1 1>&2 2>&3)

echo "CHOICE: $CHOICE"

if [ -z "$CHOICE" ]; then
	exit 0
elif [ "$CHOICE" = "0" ]; then
	MAC_ADDR=$(dialog --backtitle "WOLWizard" \
		 --title "Enter a MAC address" \
		 --inputbox "MAC address:" 7 "$WIDTH" \
		 2>&1 >/dev/tty)

else
	echo "Use MAC from history"
fi

wakeonlan "$MAC_ADDR"
