#!/bin/sh

CONFIG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/wolwizard"
HISTORY_FILE="$CONFIG_DIR/history"
FILE="$XDG_STATE_HOME"

if [ ! -f "$CONFIG_DIR" ]; then
    mkdir -p "$CONFIG_DIR"
fi

if [ -n "$WOLWIZARD_DIALOG" ]; then
    DIALOG_CMD="$WOLWIZARD_DIALOG"
elif command -v dialog >/dev/null 2>&1; then
    DIALOG_CMD="dialog"
elif command -v whiptail >/dev/null 2>&1; then
    DIALOG_CMD="whiptail"
else
    echo "No dialog tool (dialog or whiptail) found. Exiting." >&2
    exit 1
fi

WIDTH=60

i=0
MENU_ITEMS=""
HISTORY="$( [ -f "$HISTORY_FILE" ] && cat "$HISTORY_FILE" )"
while IFS= read -r line; do
	[ -z "$line" ] && continue
	MENU_ITEMS="$MENU_ITEMS $i \"$line\""
	i=$((i + 1))
done <<EOF
Enter a MAC address manually
$HISTORY
EOF


# shellcheck disable=SC2086
CHOICE=$(eval $DIALOG_CMD \
    --backtitle "\"WOLWizard\"" \
    --title "\"Select and Option\"" \
    --menu "\"Choose one\"" \
    20 $WIDTH 10 \
    $MENU_ITEMS \
    3>&1 1>&2 2>&3)

#echo "CHOICE: $CHOICE"

if [ -z "$CHOICE" ]; then
	exit 0
elif [ "$CHOICE" = "0" ]; then
    MAC_ADDR=""
    # Repeat until valid mac has been entered
    while ! echo "$MAC_ADDR" | grep -Eq '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'; do
	MAC_ADDR=$($DIALOG_CMD --backtitle "WOLWizard" \
		      --title "Enter a MAC address" \
		      --inputbox "MAC address:" 8 "$WIDTH" \
		      2>&1 >/dev/tty)
	[ -z "$MAC_ADDR" ] && exit 0
	$DIALOG_CMD --backtitle "WOLWizard" \
	       --title "Invalid MAC address" \
	       --msgbox "An invalid MAC address has been entered, try again" 7 "$WIDTH"
    done
else
    MAC_ADDR=$( echo "$HISTORY" | sed -n "$CHOICE p")
fi

# Normalize mac addr
MAC_ADDR=$(echo "$MAC_ADDR" | tr 'a-z' 'A-Z' | tr '-' ':')

HISTORY_CONTENT=$(sed "1i $MAC_ADDR" "$HISTORY_FILE" \
    | awk '!seen[$0]++' \
    | head -n 12)

printf "%s\n" "$HISTORY_CONTENT" > "$HISTORY_FILE"

wakeonlan "$MAC_ADDR"
